name: "🚀 Release"

on:
    release:
        types: [published]

jobs:
    release:
        name: 🚀 Release
        runs-on: ubuntu-latest
        steps:
            - name: 📚 Checkout
              uses: actions/checkout@v2.3.4
            - name: 🟢 Setup Node.js environment
              uses: actions/setup-node@v2.2.0
              with:
                  node-version: 14
                  registry-url: https://registry.npmjs.org
            - name: 🚀 publish
              run: npm publish --access public
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}